name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]   # tweak as desired

    steps:
      - uses: actions/checkout@v4
      
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          # Install build extra deps; no OpenAI key needed for unit tests
          pip install pynacl pyyaml click pytest
          pip install -e palobserver 

      - name: Run tests
        run: python -m pytest -q

